name = "JuliaRegistry"
uuid = "ae1ca166-2416-4e31-983b-6cbef18d4bf7"
repo = "git@github.com:ArndtLab/JuliaRegistry.git"

[packages]
0ec1a278-0482-4ecb-ba29-5ed973b8a48d = { name = "PopSimForwardSim", path = "P/PopSimForwardSim" }
1f342d77-e470-4fee-b19c-8e8d164daffc = { name = "DemoPlots", path = "D/DemoPlots" }
2104654b-de67-4eac-a5ee-be74140a16d3 = { name = "GnomADfilter", path = "G/GnomADfilter" }
3eb25097-c6d1-43fd-8407-4b1f8f9d3052 = { name = "Binnings", path = "B/Binnings" }
43ffbea4-38f1-43a5-9bfb-671206d3a474 = { name = "Cached", path = "C/Cached" }
50651ce3-0423-45d2-b99c-8ea4267d2717 = { name = "DemoInfer", path = "D/DemoInfer" }
815cba6c-817c-4129-96fa-0a4c55d2f473 = { name = "PopSimOtherTools", path = "P/PopSimOtherTools" }
88d7705d-7f72-40d5-8927-d9bc8cbe062a = { name = "PopSimIBX", path = "P/PopSimIBX" }
b0dc253a-7593-4df9-8537-7a9abf73c7af = { name = "NotebookHelper", path = "N/NotebookHelper" }
ba2eccb5-91b3-48f8-94f3-77bebdceebef = { name = "GenomicCoordinates", path = "G/GenomicCoordinates" }
be701e70-f25e-4246-ad85-09b5c637c424 = { name = "MariuxUtils", path = "M/MariuxUtils" }
cac4bed1-6c8c-4dbe-be0d-c63a427c1233 = { name = "MLDs", path = "M/MLDs" }
d7f3587b-5de0-4757-a92e-3c842e241000 = { name = "ArndtLabJuliaRegistryTools", path = "A/ArndtLabJuliaRegistryTools" }
e60d1b08-a48f-4b5c-9e89-ad4b39d64fb4 = { name = "PopSimBase", path = "P/PopSimBase" }
